# Generated by Django 3.0 on 2019-12-22 20:20

import classrooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_classroom_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='upload',
            field=models.FileField(null=True, upload_to=classrooms.models.generate_filename),
        ),
    ]
