# Generated by Django 2.2.5 on 2019-11-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_student',
            field=models.IntegerField(max_length=255, unique=True),
        ),
    ]
